# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odict < Formula
  desc ""
  homepage ""
  version "1.19.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.0/odict_1.19.0_darwin_arm64.tar.gz"
      sha256 "0f9f459e8f2803802807f49c01fb3b78b2d4b4f37d97d7186f5d203e0d88d13a"

      def install
        bin.install "odict"
        bin.install "odict-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.0/odict_1.19.0_darwin_amd64.tar.gz"
      sha256 "eff4d1fd2a88d55e5ff553025f3326e3e57520c08c9f748612e368735a9c3724"

      def install
        bin.install "odict"
        bin.install "odict-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.0/odict_1.19.0_linux_arm64.tar.gz"
      sha256 "5fa6cc29cdacfa41a52ac957d40f43bbfb9f5dd00f07fe31ddde5e5ffcde3eeb"

      def install
        bin.install "odict"
        bin.install "odict-linux-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.0/odict_1.19.0_linux_amd64.tar.gz"
      sha256 "5bd1efde7845f1c42bba6f9f3cf5f858392b6432758b5775e8c5d1c1fbc0779c"

      def install
        bin.install "odict"
        bin.install "odict-linux-amd64"
      end
    end
  end
end
