# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odict < Formula
  desc "A lightning-fast dictionary compiler and toolchain"
  homepage "https://odict.org/"
  version "1.19.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.3/odict_1.19.3_darwin_arm64.tar.gz"
      sha256 "c7f00c0b701c255f41d9e592701eab9c717fe8e41eba8378a75cddc303c7696c"

      def install
        bin.install "odict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.3/odict_1.19.3_darwin_amd64.tar.gz"
      sha256 "8fcd2cc4fdda78896bb6d955af5b8948e5b12b9f7be3ac6d96abd4542dd12e14"

      def install
        bin.install "odict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.3/odict_1.19.3_linux_arm64.tar.gz"
      sha256 "b1147598032cf40b82f57735dbab4864edd932740a8ac094c63859bea8cdec91"

      def install
        bin.install "odict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.19.3/odict_1.19.3_linux_amd64.tar.gz"
      sha256 "b00d8bcf974c5d11ef64bd6376a4855c935ae1df9ab4f837aba20ebe3226cc38"

      def install
        bin.install "odict"
      end
    end
  end
end
