# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odict < Formula
  desc "A lightning-fast dictionary compiler and toolchain"
  homepage "https://odict.org/"
  version "1.23.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.23.0/odict_1.23.0_darwin_arm64.tar.gz"
      sha256 "aee0be3c2c445e67cd34244b8549600c5c36824f8ee47384e63582059e627119"

      def install
        bin.install "odict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.23.0/odict_1.23.0_darwin_amd64.tar.gz"
      sha256 "1d366a640d2074188800554dc7eaed3f9b0752621f268cbbf8f60817442c0d4d"

      def install
        bin.install "odict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.23.0/odict_1.23.0_linux_arm64.tar.gz"
      sha256 "304a36a30e8af6f74fbf3e288608b1586d550a580c960ce63c862261cdc809b1"

      def install
        bin.install "odict"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheOpenDictionary/odict/releases/download/v1.23.0/odict_1.23.0_linux_amd64.tar.gz"
      sha256 "4e13fa30998cd2c7ce9bea7b3dd2391e167cc9ff9fdee048bd6677efbb55f1ed"

      def install
        bin.install "odict"
      end
    end
  end
end
